// packages/error-debugging/vite-overlay/examples/vite-solidjs/src/App.tsx
import { createSignal } from "solid-js";
import solidLogo from "./assets/solid.svg";
import viteLogo from "/vite.svg";
import "./App.css";

function App() {
    const [count, setCount1] = createSignal(0);

    return (
        <>
            <div>
                <a href="https://vite.dev" target="_blank">
                    <img src={viteLogo} class="logo" alt="Vite logo" />
                </a>
                <a href="https://solidjs.com" target="_blank">
                    <img src={solidLogo} class="logo solid" alt="Solid logo" />
                </a>
            </div>
            <h1>Vite + Solid</h1>
            <div class="card">
                <button onClick={() => setCount((count) => count + 1)}>count is {count()}</button>
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
            </div>
            <p class="read-the-docs">Click on the Vite and Solid logos to learn more</p>
        </>
    );
}

export default App;

// packages/error-debugging/vite-overlay/examples/vite-preact/src/app.tsx
import { useState } from "preact/hooks";
import preactLogo from "./assets/preact.svg";
import viteLogo from "/vite.svg";
import "./app.css";

export function App() {
    const [count, setCount] = useState(0);

    throw new Error("this is a message");

    return (
        <>
            <div>
                <a href="https://vite.dev" target="_blank">
                    <img src={viteLogo} class="logo" alt="Vite logo" />
                </a>
                <a href="https://preactjs.com" target="_blank">
                    <img src={preactLogo} class="logo preact" alt="Preact logo" />
                </a>
            </div>
            <h1>Vite + Preact</h1>
            <div class="card">
                <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
                <p>
                    Edit <code>src/app.tsx</code> and save to test HMR
                </p>
            </div>
            <p>
                Check out{" "}
                <a href="https://preactjs.com/guide/v10/getting-started#create-a-vite-powered-preact-app" target="_blank">
                    create-preact
                </a>
                , the official Preact + Vite starter
            </p>
            <p class="read-the-docs">Click on the Vite and Preact logos to learn more</p>
        </>
    );
}
