// packages/error-debugging/dev-toolbar/examples/vite-svelte/src/App.svelte
<script lang="ts">
    import svelteLogo from "./assets/svelte.svg";
    import viteLogo from "/vite.svg";
    import Counter from "./lib/Counter.svelte";

    const throwError = () => {
        setTimeout(() => {
            const cause = new TypeError("Cannot read properties of undefined (reading 'name')");
            const err = new Error("Example client error thrown from the Svelte dev-toolbar demo");

            err.cause = cause;
            throw err;
        }, 0);
    };

    const rejectPromise = () => {
        void Promise.reject(new Error("Example unhandled Promise rejection from the Svelte dev-toolbar demo"));
    };
</script>

<main>
    <div>
        <a href="https://vite.dev" target="_blank" rel="noreferrer">
            <img src={viteLogo} class="logo" alt="Vite Logo" />
        </a>
        <a href="https://svelte.dev" target="_blank" rel="noreferrer">
            <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
        </a>
    </div>
    <h1>Vite + Svelte + Dev Toolbar</h1>

    <div class="card">
        <Counter />
    </div>

    <div class="card">
        <button onclick={throwError}>Throw Error</button>
        <button onclick={rejectPromise}>Unhandled Rejection</button>
    </div>

    <p>
        Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by
        Vite!
    </p>

    <p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
    .logo {
        height: 6em;
        padding: 1.5em;
        will-change: filter;
        transition: filter 300ms;
    }
    .logo:hover {
        filter: drop-shadow(0 0 2em #646cffaa);
    }
    .logo.svelte:hover {
        filter: drop-shadow(0 0 2em #ff3e00aa);
    }
    .read-the-docs {
        color: #888;
    }
</style>

// packages/error-debugging/dev-toolbar/examples/vite-cloudflare/src/App.tsx
import "./App.css";

import { useState } from "react";

import viteLogo from "/vite.svg";
import reactLogo from "./assets/react.svg";

function App() {
    const [count, setCount] = useState(0);

    const throwError = () => {
        setTimeout(() => {
            const cause = new TypeError("Cannot read properties of undefined (reading 'name')");
            const err = new Error("Example client error thrown from the Cloudflare dev-toolbar demo");

            err.cause = cause;
            throw err;
        }, 0);
    };

    const rejectPromise = () => {
        void Promise.reject(new Error("Example unhandled Promise rejection from the Cloudflare dev-toolbar demo"));
    };

    return (
        <>
            <div>
                <a href="https://vite.dev" target="_blank">
                    <img alt="Vite logo" className="logo" src={viteLogo} />
                </a>
                <a href="https://react.dev" target="_blank">
                    <img alt="React logo" className="logo react" src={reactLogo} />
                </a>
            </div>
            <h1>Vite + React + Cloudflare + Dev Toolbar</h1>
            <div className="card">
                <button type="button" onClick={() => setCount((c) => c + 1)}>
                    count is {count}
                </button>
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
            </div>
            <div className="card">
                <button type="button" onClick={throwError}>
                    Throw Error
                </button>{" "}
                <button type="button" onClick={rejectPromise}>
                    Unhandled Rejection
                </button>
            </div>
            <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
        </>
    );
}

export default App;
