// packages/storage-client/examples/nuxt/app.vue
<template>
    <div class="app">
        <h1>Storage Client - Nuxt Example</h1>
        <div class="upload-section">
            <input type="file" @change="handleFileChange" :disabled="isUploading" />
            <button @click="handleUpload" :disabled="!file || isUploading">
                {{ isUploading ? "Uploading..." : "Upload" }}
            </button>
            <button @click="handleReset" :disabled="isUploading">
                Reset
            </button>
        </div>
        <div v-if="isUploading" class="progress-section">
            <div>Progress: {{ progress }}%</div>
            <progress :value="progress" max="100" />
        </div>
        <div v-if="error" class="error">Error: {{ error.message }}</div>
        <div v-if="result" class="success">
            Upload complete! File: {{ result.filename }}
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import { useUpload } from "@visulima/storage-client/vue";

const file = ref<File | null>(null);
const { upload, progress, isUploading, error, result, reset } = useUpload({
    endpointMultipart: "/api/upload/multipart",
    endpointTus: "/api/upload/tus",
    onSuccess: (result) => {
        console.log("Upload successful:", result);
    },
    onError: (error_) => {
        console.error("Upload error:", error_);
    },
});

const handleFileChange = (e: Event) => {
    const target = e.target as HTMLInputElement;
    const selectedFile = target.files?.[0];
    file.value = selectedFile || null;
};

const handleUpload = async () => {
    if (file.value) {
        try {
            await upload(file.value);
        } catch (error_) {
            console.error("Upload failed:", error_);
        }
    }
};

const handleReset = () => {
    reset();
    file.value = null;
    const fileInput = document.querySelector('input[type="file"]') as HTMLInputElement;
    if (fileInput) {
        fileInput.value = "";
    }
};
</script>

<style scoped>
.app {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    text-align: center;
}

.upload-section {
    margin: 2rem 0;
    display: flex;
    gap: 1rem;
    justify-content: center;
    align-items: center;
}

.upload-section input[type="file"] {
    padding: 0.5rem;
}

.upload-section button {
    padding: 0.5rem 1rem;
    background-color: #00dc82;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

.upload-section button:disabled {
    background-color: #ccc;
    cursor: not-allowed;
}

.progress-section {
    margin: 2rem 0;
}

.progress-section progress {
    width: 100%;
    max-width: 400px;
    height: 20px;
}

.error {
    margin: 1rem 0;
    padding: 1rem;
    background-color: #fee;
    color: #c33;
    border-radius: 4px;
}

.success {
    margin: 1rem 0;
    padding: 1rem;
    background-color: #efe;
    color: #3c3;
    border-radius: 4px;
}
</style>

// packages/storage-client/examples/react/src/App.tsx
import "./App.css";

import { useUpload } from "@visulima/storage-client/react";
import { useState } from "react";

const App = () => {
    const [file, setFile] = useState<File | null>(null);
    const { error, isUploading, progress, result, upload } = useUpload({
        endpointMultipart: "/api/upload/multipart",
        endpointTus: "/api/upload/tus",
        onError: (error_) => {
            console.error("Upload error:", error_);
        },
        onSuccess: (result) => {
            console.log("Upload successful:", result);
        },
    });

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const selectedFile = e.target.files?.[0];

        setFile(selectedFile || null);
    };

    const handleUpload = async () => {
        if (file) {
            try {
                await upload(file);
            } catch (error_) {
                console.error("Upload failed:", error_);
            }
        }
    };

    return (
        <div class="app">
            <h1>Storage Client - React Example</h1>
            <div class="upload-section">
                <input disabled={isUploading} onChange={handleFileChange} type="file" />
                <button disabled={!file || isUploading} onClick={handleUpload}>
                    {isUploading ? "Uploading..." : "Upload"}
                </button>
            </div>
            {isUploading && (
                <div class="progress-section">
                    <div>
                        Progress:
                        {progress}
                        %
                    </div>
                    <progress max={100} value={progress} />
                </div>
            )}
            {error && (
                <div class="error">
                    Error:
                    {error.message}
                </div>
            )}
            {result && (
                <div class="success">
                    Upload complete! File:
                    {result.filename}
                </div>
            )}
        </div>
    );
};

export default App;
