// packages/storage-client/examples/tanstack-start/src/routes/__root.tsx
import { createRootRoute, HeadContent, Scripts } from "@tanstack/react-router";

const RootDocument = ({ children }: { children: React.ReactNode }) => (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
);

export const Route = createRootRoute({
    head: () => {
        return {
            meta: [
                {
                    charSet: "utf-8",
                },
                {
                    content: "width=device-width, initial-scale=1",
                    name: "viewport",
                },
                {
                    title: "Storage Upload Example - TanStack Start",
                },
            ],
        };
    },

    shellComponent: RootDocument,
});

// packages/storage-client/examples/solid-start/app/root.tsx
import "./app.css";

import { Links, Meta, Scripts, Title } from "@solidjs/start";
import { Suspense } from "solid-js";

export default function Root() {
    return (
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta content="width=device-width, initial-scale=1" name="viewport" />
                <Meta />
                <Links />
                <Title>Storage Client - Solid Start Example</Title>
            </head>
            <body>
                <Suspense>
                    <div id="app" />
                </Suspense>
                <Scripts />
            </body>
        </html>
    );
}
